components/level/game.tsx
styles/global.css

https://user-images.githubusercontent.com/965260/168452053-61cdf6a9-bfdf-4062-bc6c-1cd8460c32e3.mov

Fixes #82 - Add Gesture Controls for Mobile

---

components/level/game.tsx
components/universeTable.tsx
pages/profile/[id].tsx

- more condensed stats on profile
- game should not refresh if leastMoves updates with SWR

profile cleanup + game bug fix

---

components/level/game.tsx
helpers/cloneLevel.ts
models/db/level.ts
models/schemas/levelSchema.ts
pages/api/level-by-id/[id].ts
pages/level/[id].tsx

- remove officialUserId everywhere (step 2 and 3 of #125)
- remove worldId from level page (no world/universe info on level page now)

Remove officialUserId

---

components/page.tsx

isFallback isn't properly supported:
https://github.com/vercel/next.js/discussions/23992#discussioncomment-2830971
workaround:
https://github.com/vercel/next.js/discussions/23992#discussioncomment-599834

loading animation for level page

---

.github/workflows/node.js.yml
helpers/discordWebhook.ts
lib/cookieOptions.ts
lib/dbConnect.ts
lib/isLocal.ts
lib/withAuth.ts
pages/api/login/index.ts
pages/api/logout/index.ts
pages/api/signup/index.ts
pages/api/user/index.ts
pages/level/[id].tsx
pages/universe/[id].tsx
pages/world/[id].tsx
tests/env.test.ts

https://user-images.githubusercontent.com/965260/171651856-aa7a8d56-35da-4eed-a738-82c55e7a9cbc.mov

Issue #6 Refresh cookie every auth

---

components/select.tsx

https://user-images.githubusercontent.com/965260/174330594-a25238aa-4886-4b2b-9855-3cc4f80f08e9.mov

hopefully fixes sorting

---

components/level/game.tsx
components/menu/dropdown.tsx
pages/level/[username]/[slugName].tsx
pages/test/[id].tsx

- fix author note popping up in game when the level updates from SWR
- update least moves on test page when you set a record

misc game fixes

---

hooks/useWindowSize.ts

try visual viewport instead of innerheight since it contains an unrounded number

Scrollbars when browser is scaled

---

components/formattedReview.tsx
components/level/gameLayout.tsx
components/level/sidebar.tsx
components/loginForm.tsx
components/modal/authorNoteModal.tsx
components/modal/index.tsx
components/modal/publishLevelModal.tsx
helpers/cleanAuthorNote.ts
helpers/formatAuthorNote.tsx
models/schemas/levelSchema.ts
pages/api/search.ts
pages/edit/world/[id].tsx
pages/world/[id].tsx

- word wrap for reviews and sidebar
- format author note everywhere
- background blur when modal is open
- allow apostrophe in search string
- allow saving 40x40 levels
- fix regression of win animation showing scroll bars
- fix flex bug with login buttons

misc bug fixes

---

components/editor.tsx
components/level/controls.tsx
components/level/game.tsx
components/levelTable.tsx
components/worldTable.tsx
constants/dimensions.ts
models/control.ts

Game:
Editor:
Can update as needed but these should be ok for now

Svg controls

---

components/editor.tsx
components/level/controls.tsx
components/level/game.tsx
components/levelTable.tsx
components/worldTable.tsx
constants/dimensions.ts
models/control.ts

Revert "Svg controls"

---

models/schemas/userSchema.ts
package-lock.json
package.json

Revert "next v12.2.1"

---

components/SelectCard.module.css
components/selectCard.tsx
models/schemas/userSchema.ts
pages/api/level/image/[id].ts
styles/global.css
tests/pages/api/level/level.image.test.ts

https://user-images.githubusercontent.com/965260/178123710-6c86a7d7-439d-4480-a217-988bf4a4dbd2.mov

Image preview and updated hover effect for level selection

---

components/SelectCard.module.css
components/select.tsx
components/selectCard.tsx
constants/dimensions.ts

SelectCard improvements

---

components/homeDefault.tsx
components/homeLoggedIn.tsx
components/level/game.tsx
pages/tutorial.tsx

- home page icon updates
- onMove instead of onPlayerInput for tutorial
- a few updates to tutorial texts

Home page + tutorial updates

---

pages/api/search.ts
pages/search/index.tsx
pages/world/[id].tsx
tests/pages/api/search.test.ts

World list table

---

helpers/revalidateLevel.ts
helpers/revalidateUniverse.ts
pages/api/level/[id].ts
pages/api/publish/[id].ts
pages/api/revalidate/level/[username]/[slugName].ts
pages/api/unpublish/[id].ts
pages/api/user/index.ts
pages/api/world/[id].ts

Revalidate the level page when a level is published/unpublished/deleted

revalidate level

---

Dockerfile

Updated dockerfile to address a permission error with the .next dir

Updated dockerfile to address a permission error with the .next dir

---

components/modal/publishLevelModal.tsx
components/modal/sizeModal.tsx
pages/search/index.tsx

- show current best step count for in-progress levels on search page
- allow empty string in number inputs
- size modal error messages
- publish modal keys

misc improvements

---

.github/workflows/update-production.yml

Input sanitize ( pathology-server #36)

---

Dockerfile

Updated the production Dockerfile to a multi-stage build with a smaller image at the end. Also minimized what ends up on the final image. Reduces image size, and reduces potential attack vectors

Updated the production Dockerfile

---

components/level/game.tsx
pages/api/user-config/index.ts
pages/index.tsx
pages/tutorial/index.tsx

- simplify restricted movable intro level
- rename 'end square' to 'exit' everywhere
- various instructions improvements
- set tutorialCompletedAt after finishing tutorial
- different message after completing tutorial if you are logged in
- play/campaign is based on tutorialCompletedAt

tutorial fixes

---

components/level/Controls.module.css
components/level/game.tsx
pages/level/[username]/[slugName].tsx
pages/test/[id].tsx
pages/tutorial/index.tsx

- red glow for restart/undo if you have made too many moves
- no free undo in tutorial
- allow closing popper (small resolutions may cause it to cover prev/next buttons)
- improved instructional text throughout tutorial

tutorial tweaks

---

.github/workflows/build-and-publish.yml
.github/workflows/node.js.yml
Dockerfile

setting dummy NR values during the build and test actions

New Relic Dummy Values

---

components/level/Player.module.css
components/level/square.tsx
pages/_document.tsx
styles/global.css

- spinning player character
- stepcount font update

Pp1 theme updates

---

components/modal/index.tsx

- Remove deprecated `Dialog.Overlay`
- Use `Dialog.Panel`
- Remove `windowSize` dependency

Modal updates

---

pages/api/internal-jobs/email-digest/index.tsx
tests/pages/api/internal-jobs/email-digest.test.ts

- Update all email colors to look normal on light mode (so that clients that invert on dark mode also look correct)
- Simplify email sending logic

daily emails; style updates

---

components/avatar.tsx
components/formattedLevelReviews.tsx
components/homeVideo.tsx
components/level/game.tsx
components/loginForm.tsx
components/menu/dropdown.tsx
components/menu/index.tsx
components/menu/notificationsButton.tsx
components/menu/userInfo.tsx
components/modal/addLevelModal.tsx
components/modal/deleteCollectionModal.tsx
components/modal/deleteLevelModal.tsx
components/modal/publishLevelModal.tsx
components/modal/themeModal.tsx
components/modal/unpublishLevelModal.tsx
components/page.tsx
components/reviewForm.tsx
components/selectFilter.tsx
components/settingsForm.tsx
components/statisticsTable.tsx
components/tutorial.tsx
components/uploadImage.tsx
contexts/appContext.ts
contexts/pageContext.ts
pages/_app.tsx
pages/create/index.tsx
pages/edit/collection/[id].tsx
pages/level/[username]/[slugName].tsx
pages/notifications/index.tsx

mutating user when it exists in `_app.tsx` doesn't cause a rerender, need to move a level down into the page context for it to work correctly
also updated login redirect to /home

Move user to PageContext

---

components/homeDefault.tsx
components/homeVideo.tsx
helpers/getPngDataClient.ts

- max width for homedefault text so it looks fine on large screens
- brighter + centered figure captions
- homevideo no longer crops text on high zoom
- bigger play button

home css updates

---

components/formattedReview.tsx
components/level/gameWrapper.tsx
components/modal/dataModal.tsx
pages/api/stats/index.ts
pages/play/index.tsx
pages/profile/[name]/[[...tab]]/index.tsx
pages/search/index.tsx
pages/statistics/[[...route]]/index.tsx
pages/tutorial/index.tsx

- improve FormattedReview styling
- fix editor data whitespace trim bug
- revalidate level on new record
- play page css
- NextSeo on a few pages
- verify user has loaded before showing sign up toast

various fixes

---

helpers/getDifficultyEstimate.ts
tests/helpers/helpers.test.ts
tests/pages/api/play-attempt/play-attempt.test.ts

refining of difficulty scaling attempt 1

---

.github/workflows/build-and-publish.yml

Also it will kick off a build I can compare build times

Updated version of the docker actions

---

components/homeLoggedIn.tsx
hooks/useHomePageData.ts
pages/api/home/index.ts
pages/home/index.tsx
pages/profile/[name]/[[...tab]]/index.tsx
tests/pages/api/home/home.test.ts

merge once this query is empty - https://pathology.gg/search?difficultyFilter=Pending&sortBy=calcDifficultyEstimate&timeRange=All

suggest unattempted by solve count

---

components/editor.tsx
components/level/square.tsx
components/theme/monkey.tsx
styles/global.css

Extra text fix contrast

---

components/level/game.tsx
components/level/gameLayout.tsx
components/modal/checkpointsModal.tsx
components/tutorial.tsx
contexts/gameContext.ts
helpers/apiWrapper.ts
helpers/checkpointHelpers.ts
helpers/gameStateHelpers.ts
hooks/useCheckpoints.ts
pages/api/level/[id]/checkpoints/index.ts
server/scripts/convert-checkpoints.ts
tests/pages/api/level/[id]/checkpoint.test.ts

- checkpoints are now saved as `Direction[]` instead of `CheckpointState`
- `SessionCheckpointState` has been updated to reflect this as well
- loading user checkpoints or session checkpoints handles both `Direction[]` and `CheckpointState`
- refactor `GameState` functions into `gameStateHelpers.ts`

Save checkpoints as Direction[]

---

.eslintrc.json
components/enrichedLevelLink.tsx
components/formattedLevelReviews.tsx
components/formattedReview.tsx
components/header/dropdown.tsx
components/reviewDropdown.tsx
components/reviewForm.tsx
package-lock.json
package.json

review style updates

---

pages/api/stripe-webhook/index.ts
tests/pages/api/stripe/stripe-webhook.test.ts

Upon a successful payment intent (new or renewing subscriptions):
- Determine the net earnings after Stripe fees
- Split the total and transfer this amount to the connected account

Stripe Connected Account

---

components/counters/AnimateCounterOne.tsx
components/counters/Counter.tsx
components/formatted/formattedUser.tsx
components/gameLogo.tsx
constants/alertType.ts
helpers/enrich.ts
lib/appSocketToClient.ts
lib/withAuth.ts
models/db/user.d.ts
models/db/userConfig.d.ts
models/schemas/userConfigSchema.ts
package-lock.json
package.json
pages/[subdomain]/profile/[name]/[[...tab]]/index.tsx
pages/_app.tsx
pages/api/internal-jobs/worker/index.ts
pages/api/play-attempt/index.ts
pages/api/streak/index.ts
server/socket/socketFunctions.ts
styles/global.css
tests/pages/api/match/matchCreateJoinAndPlay.test.ts
tests/pages/api/match/matchCreateJoinAndQuit.test.ts
tests/pages/api/user/user.test.ts

make streaks more first class
https://github.com/user-attachments/assets/1266ffbb-ed98-4dbe-b03d-104e80e5add9

add streak indicators
